version: "3.7"

networks:
  default:
    driver: bridge

services:
  myapp:
    image: myapp
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    restart: always
    env_file:
      - .dockerenv
    command:
      "./start runserver"
    # volumes:
    #   - 'ckchina_search_log:/app/logs'
  
  myxray:
    image: xray
    build:
      context: .
      dockerfile: Dockerfile.xray
    container_name: xray
    restart: always
    env_file:
      - .dockerenv

  nginx:
    image: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    env_file:
      - .dockerenv 
    ports:
      - "8088:${PORT}"
    depends_on:
      - myapp
      - myxray    
