apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/xray:latest
        name: ray
        env:
        - name: Vless_UUID
          value: "$Vless_UUID"
        - name: Vless_Path
          value: "$Vless_Path"
        - name: Vmess_UUID
          value: "$Vmess_UUID"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"

      - name: nginx
        image: okteto.dev/nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: PORT
          value: "80"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "$Vless_UUID"
        - name: Vless_Path
          value: "$Vless_Path"
        - name: Vmess_UUID
          value: "$Vmess_UUID"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"
        - name: APP_ADD
          value: "$APP_ADD"
        - name: XRAY_ADD
          value: "$XRAY_ADD"
        - name: BARK_KEY
          value: "$BARK_KEY"

      - name: app
        image: okteto.dev/myapp:latest
        command:
          - "/bin/bash"
          - "-ce"
          - "./start runserver"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: SS_URL
          value: "$SS_URL"
        - name: V2_URL
          value: "$V2_URL"
      - name: bark
        image: finab/bark-server:2.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: BARK_KEY
          value: "$BARK_KEY"
        - name: BARK_DEVICE_TOKEN
          value: "$BARK_DEVICE_TOKEN"
