jobs:
  run:
    name: Update
    runs-on: ubuntu-latest

    steps:
      # If you need to, you can check out your repo to a different location
      - uses: actions/checkout@v2

      # You can make whatever type of change to the repo...
      - run: make clean

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'update version'
          add: 'src/version.py --force'
          
